import { Topic } from './types';

export const VOCABULARY_DATA: Topic[] = [
  {
    id: 'jobs',
    name: '1. Chủ đề nghề nghiệp',
    words: [
      { en: 'Actor/ Actress', vn: 'Diễn viên nam/ nữ' },
      { en: 'Architect', vn: 'Kiến trúc sư' },
      { en: 'Astronaut', vn: 'Phi hành gia' },
      { en: 'Athlete', vn: 'Vận động viên' },
      { en: 'Banker', vn: 'Nhân viên ngân hàng' },
      { en: 'Business man/ woman', vn: 'Nam/ nữ doanh nhân' },
      { en: 'Chef', vn: 'Đầu bếp' },
      { en: 'Chemist', vn: 'Nhà hoá học' },
      { en: 'Dancer', vn: 'Vũ công' },
      { en: 'Dentist', vn: 'Nha sĩ' },
      { en: 'Doctor', vn: 'Bác sĩ' },
      { en: 'Employee', vn: 'Nhân viên' },
      { en: 'Engineer', vn: 'Kĩ sư' },
      { en: 'Housewife', vn: 'Nội trợ' },
      { en: 'Lawyer', vn: 'Luật sư' },
      { en: 'Manager', vn: 'Giám đốc, quản lí' },
      { en: 'Nurse', vn: 'Y tá' },
      { en: 'Policeman', vn: 'Công an, cảnh sát' },
      { en: 'Programmer', vn: 'Lập trình viên' },
      { en: 'Student', vn: 'Học sinh, sinh viên' },
      { en: 'Teacher', vn: 'Giáo viên' }
    ]
  },
  {
    id: 'sports',
    name: '2. Chủ đề thể thao',
    words: [
      { en: 'Badminton', vn: 'Cầu lông' },
      { en: 'Baseball', vn: 'Bóng chày' },
      { en: 'Basketball', vn: 'Bóng rổ' },
      { en: 'Boxing', vn: 'Đấm bốc' },
      { en: 'Championship', vn: 'Giải vô địch' },
      { en: 'Club', vn: 'Câu lạc bộ' },
      { en: 'Competition', vn: 'Cuộc thi đấu' },
      { en: 'Diving', vn: 'Lặn' },
      { en: 'Game', vn: 'Cuộc đấu' },
      { en: 'Gymnastics', vn: 'Thể dục thể hình' },
      { en: 'Jogging', vn: 'Đi bộ' },
      { en: 'Motor-racing', vn: 'Đua mô tô' },
      { en: 'Race', vn: 'Cuộc đua' },
      { en: 'Score', vn: 'Tỉ số' },
      { en: 'Skating', vn: 'Trượt ván' },
      { en: 'Stadium', vn: 'Sân vận động' },
      { en: 'Table tennis', vn: 'Bóng bàn' },
      { en: 'Team', vn: 'Đội' },
      { en: 'Tennis', vn: 'Quần vợt' },
      { en: 'Water skiing', vn: 'Lướt sóng' }
    ]
  },
  {
    id: 'education',
    name: '3. Chủ đề giáo dục',
    words: [
      { en: 'Absence', vn: 'Sự vắng mặt' },
      { en: 'Art', vn: 'Nghệ thuật, mĩ thuật' },
      { en: 'Blackboard', vn: 'Bảng đen' },
      { en: 'Book', vn: 'Sách' },
      { en: 'Bookshelf', vn: 'Giá sách' },
      { en: 'Certificate', vn: 'Chứng chỉ' },
      { en: 'Chemistry', vn: 'Hoá học' },
      { en: 'Class', vn: 'Lớp học' },
      { en: 'Coach', vn: 'Huấn luyện viên' },
      { en: 'Course', vn: 'Khoá học' },
      { en: 'Curriculum', vn: 'Chương trình học' },
      { en: 'Desk', vn: 'Bàn học' },
      { en: 'Dictionary', vn: 'Từ điển' },
      { en: 'Economics', vn: 'Kinh tế học' },
      { en: 'IT (Information technology)', vn: 'Công nghệ thông tin' },
      { en: 'Laboratory', vn: 'Phòng nghiên cứu' },
      { en: 'Lesson', vn: 'Tiết học, bài học' },
      { en: 'Library', vn: 'Thư viện' },
      { en: 'Mark', vn: 'Điểm' },
      { en: 'Mathematics', vn: 'Toán học' },
      { en: 'Music', vn: 'Âm nhạc' },
      { en: 'Pen', vn: 'Bút' },
      { en: 'Pencil', vn: 'Bút chì' },
      { en: 'Physics', vn: 'Vật lí' },
      { en: 'Practice', vn: 'Thực hành' },
      { en: 'Qualification', vn: 'Bằng cấp' },
      { en: 'Research', vn: 'Nghiên cứu' },
      { en: 'Ruler', vn: 'Thước kẻ' },
      { en: 'School', vn: 'Trường học' },
      { en: 'Science', vn: 'Khoa học' },
      { en: 'Term', vn: 'Học kì' },
      { en: 'Test', vn: 'Bài kiểm tra' },
      { en: 'University', vn: 'Đại học' }
    ]
  },
  {
    id: 'health',
    name: '4. Chủ đề sức khoẻ',
    words: [
      { en: 'Asthma', vn: 'Hen, xuyễn' },
      { en: 'Backache', vn: 'Đau lưng' },
      { en: 'Boil', vn: 'Mụn nhọt' },
      { en: 'Broken bone', vn: 'Gãy xương' },
      { en: 'Burn', vn: 'Bỏng' },
      { en: 'Cancer', vn: 'Ung thư' },
      { en: 'Chicken pox', vn: 'Thủy đậu' },
      { en: 'Cold', vn: 'Cảm lạnh' },
      { en: 'Depression', vn: 'Trầm cảm' },
      { en: 'Diabetes', vn: 'Tiểu đường' },
      { en: 'Fever virus', vn: 'Sốt siêu vi' },
      { en: 'Food poisoning', vn: 'Ngộ độc thực phẩm' },
      { en: 'Flu', vn: 'Cúm' },
      { en: 'Allergy', vn: 'Dị ứng' },
      { en: 'Infect', vn: 'Nhiễm trùng' },
      { en: 'Gout', vn: 'Bệnh gút' },
      { en: 'Hepatitis', vn: 'Viêm gan' },
      { en: 'Headache', vn: 'Đau đầu' },
      { en: 'Heart attack', vn: 'Đau tim/ Nhồi máu cơ tim' },
      { en: 'High blood pressure', vn: 'Huyết áp cao' },
      { en: 'Low blood pressure', vn: 'Huyết áp thấp' },
      { en: 'Lump', vn: 'U bướu' },
      { en: 'Lung cancer', vn: 'Ung thư phổi' },
      { en: 'Malaria', vn: 'Sốt rét' },
      { en: 'Measles', vn: 'Sởi' },
      { en: 'Mumps', vn: 'Quai bị' },
      { en: 'Pneumonia', vn: 'Viêm phổi' },
      { en: 'Rheumatism', vn: 'Thấp khớp' },
      { en: 'Scabies', vn: 'Ghẻ' },
      { en: 'Sore throat', vn: 'Viêm họng' },
      { en: 'Sprain', vn: 'Bong gân' },
      { en: 'Stomach ache', vn: 'Đau dạ dày' },
      { en: 'Skin-disease', vn: 'Bệnh ngoài da' },
      { en: 'Smallpox', vn: 'Đậu mùa' },
      { en: 'Tuberculosis', vn: 'Bệnh lao' }
    ]
  },
  {
    id: 'colors',
    name: '5. Chủ đề màu sắc',
    words: [
      { en: 'Beige', vn: 'Màu be' },
      { en: 'Black', vn: 'Màu đen' },
      { en: 'Blue', vn: 'Màu xanh dương' },
      { en: 'Bright red', vn: 'Màu đỏ tươi' },
      { en: 'Bright green', vn: 'Màu xanh lá cây tươi' },
      { en: 'Brown', vn: 'Màu nâu' },
      { en: 'Dark brown', vn: 'Màu nâu đậm' },
      { en: 'Dark green', vn: 'Màu xanh lá cây đậm' },
      { en: 'Gray', vn: 'Màu xám' },
      { en: 'Green', vn: 'Màu xanh lá cây' },
      { en: 'Light blue', vn: 'Màu xanh dương nhạt' },
      { en: 'Light brown', vn: 'Màu nâu nhạt' },
      { en: 'Light green', vn: 'Màu xanh lá cây nhạt' },
      { en: 'Orange', vn: 'Màu cam' },
      { en: 'Pink', vn: 'Màu hồng' },
      { en: 'Purple', vn: 'Màu tím' },
      { en: 'Red', vn: 'Màu đỏ' },
      { en: 'Violet', vn: 'Màu tím' },
      { en: 'White', vn: 'Màu trắng' },
      { en: 'Yellow', vn: 'Màu vàng' }
    ]
  },
  {
    id: 'clothing',
    name: '6. Chủ đề trang phục',
    words: [
      { en: 'Boots', vn: 'Bốt/ Cao cổ' },
      { en: 'Chunky heel', vn: 'Cao gót đế thô' },
      { en: 'Clog', vn: 'Guốc' },
      { en: 'Loafer', vn: 'Giày lười' },
      { en: 'Sandals', vn: 'Xăng-đan' },
      { en: 'Sneaker', vn: 'Giày thể thao' },
      { en: 'Stilettos', vn: 'Giày gót nhọn' },
      { en: 'Wedge boot', vn: 'Giày đế xuồng' },
      { en: 'Balaclava', vn: 'Mũ len trùm đầu' },
      { en: 'Baseball cap', vn: 'Mũ lưỡi trai' },
      { en: 'Beret', vn: 'Mũ nồi' },
      { en: 'Bucket hat', vn: 'Mũ tai bèo' },
      { en: 'Cowboy hat', vn: 'Mũ cao bồi' },
      { en: 'Hard hat', vn: 'Mũ bảo hộ' },
      { en: 'Helmet', vn: 'Mũ bảo hiểm' },
      { en: 'Anorak', vn: 'Áo khoác có mũ' },
      { en: 'Bathrobe', vn: 'Áo choàng tắm' },
      { en: 'Belt', vn: 'Thắt lưng' },
      { en: 'Blouse', vn: 'Sơ mi nữ' },
      { en: 'Boxer shorts', vn: 'Quần đùi' },
      { en: 'Bra', vn: 'Áo lót nữ' },
      { en: 'Cardigan', vn: 'Áo len cài đằng trước' },
      { en: 'Coat', vn: 'Áo khoác' },
      { en: 'Dress', vn: 'Váy liền' },
      { en: 'Gloves', vn: 'Găng tay' },
      { en: 'Jacket', vn: 'Áo khoác ngắn' },
      { en: 'Jeans', vn: 'Quần bò' },
      { en: 'Jumper', vn: 'Áo len' },
      { en: 'Knickers', vn: 'Quần lót nữ' },
      { en: 'Nightie', vn: 'Váy ngủ' },
      { en: 'Overcoat', vn: 'Áo măng tô' },
      { en: 'Pants', vn: 'Quần Âu' },
      { en: 'Pullover', vn: 'Áo len chui đầu' },
      { en: 'Pyjamas', vn: 'Bộ đồ ngủ' },
      { en: 'Raincoat', vn: 'Áo mưa' },
      { en: 'Scarf', vn: 'Khăn quàng' },
      { en: 'Shirt', vn: 'Sơ mi' },
      { en: 'Shorts', vn: 'Quần sooc' },
      { en: 'Skirt', vn: 'Chân váy' },
      { en: 'Suit', vn: 'Com lê' },
      { en: 'Swimming costume', vn: 'Đồ bơi' },
      { en: 'Tie', vn: 'Cà vạt' },
      { en: 'Trousers', vn: 'Quần dài' },
      { en: 'T-shirt', vn: 'Áo phông' },
      { en: 'Underpants', vn: 'Quần lót nam' }
    ]
  },
  {
    id: 'drinks',
    name: '7. Chủ đề đồ uống',
    words: [
      { en: 'Ale', vn: 'Bia tươi' },
      { en: 'Aperitif', vn: 'Rượu khai vị' },
      { en: 'Beer', vn: 'Bia' },
      { en: 'Brandy', vn: 'Rượu brandi' },
      { en: 'Champagne', vn: 'Sâm panh' },
      { en: 'Cider', vn: 'Rượu táo' },
      { en: 'Cocktail', vn: 'Cooc tai' },
      { en: 'Gin', vn: 'Rượu gin' },
      { en: 'Lager', vn: 'Bia vàng' },
      { en: 'Lime cordial', vn: 'Rượu chanh' },
      { en: 'Liqueur', vn: 'Rượu mùi' },
      { en: 'Martini', vn: 'Rượu mac-ti-ni' },
      { en: 'Red wine', vn: 'Vang đỏ' },
      { en: 'Rose', vn: 'Rựu nho hồng' },
      { en: 'Rum', vn: 'Rượu rum' },
      { en: 'Shandy', vn: 'Bia pha nước chanh' },
      { en: 'Sparkling wine', vn: 'Rượu có ga' },
      { en: 'Vodka', vn: 'Rượu vodka' },
      { en: 'White wine', vn: 'Vang trắng' },
      { en: 'Whisky', vn: 'Rượu whisky' }
    ]
  },
  {
    id: 'places',
    name: '8. Chủ đề địa điểm',
    words: [
      { en: 'Bank', vn: 'Ngân hàng' },
      { en: 'Bookstore', vn: 'Hiệu sách' },
      { en: 'Café', vn: 'Quán cà phê' },
      { en: 'Cinema', vn: 'Rạp chiếu phim' },
      { en: 'College', vn: 'Trường cao đẳng' },
      { en: 'Factory', vn: 'Nhà máy' },
      { en: 'Garage', vn: 'Ga-ra' },
      { en: 'Grocery store', vn: 'Cửa hàng tạp hoá' },
      { en: 'Guest-house', vn: 'Nhà khách' },
      { en: 'Hospital', vn: 'Bệnh viện' },
      { en: 'Mall', vn: 'Trung tâm thương mại' },
      { en: 'Museum', vn: 'Bảo tàng' },
      { en: 'Prison', vn: 'Nhà tu' },
      { en: 'Railway station', vn: 'Nhà ga tàu hoà' },
      { en: 'School', vn: 'Trường học' },
      { en: 'Sports centre', vn: 'Trung tâm thể thao' },
      { en: 'Stadium', vn: 'Sân vận động' },
      { en: 'Supermarket', vn: 'Siêu thị' },
      { en: 'Theatre', vn: 'Nhà hát' },
      { en: 'University', vn: 'Đại học' }
    ]
  },
  {
    id: 'city',
    name: '9. Chủ đề thành phố',
    words: [
      { en: 'Apartment building', vn: 'Toà chung cư' },
      { en: 'Airport', vn: 'Sân bay' },
      { en: 'Bridge', vn: 'Cầu' },
      { en: 'Bus station', vn: 'Điểm dừng xe buýt' },
      { en: 'Car park', vn: 'Điểm đỗ ô tô' },
      { en: 'City centre', vn: 'Trung tâm thành phố' },
      { en: 'Park', vn: 'Công viên' },
      { en: 'Shopping centre', vn: 'Trung tâm mua sắm' },
      { en: 'Subway', vn: 'Đường tàu' },
      { en: 'Zoo', vn: 'Sở thú' },
      { en: 'Services', vn: 'Dịch vụ' },
      { en: 'Bank', vn: 'Ngân hàng' },
      { en: 'Hotel', vn: 'Khách sạn' },
      { en: 'Hairdresser', vn: 'Tiệm tóc' },
      { en: 'Post office', vn: 'Bưu điện' },
      { en: 'Restaurant', vn: 'Quán ăn' },
      { en: 'Swimming pool', vn: 'Hồ bơi' }
    ]
  },
  {
    id: 'countryside',
    name: '10. Chủ đề nông thôn',
    words: [
      { en: 'Area', vn: 'Khu vực' },
      { en: 'Bay', vn: 'Vịnh' },
      { en: 'Campsite', vn: 'Khu cắm trại' },
      { en: 'Canal', vn: 'Kênh, rạch' },
      { en: 'Farm', vn: 'Nông trại' },
      { en: 'Field', vn: 'Cánh đồng' },
      { en: 'Forest', vn: 'Rừng' },
      { en: 'Island', vn: 'Đảo' },
      { en: 'Lake', vn: 'Hồ' },
      { en: 'Mountain', vn: 'Núi' },
      { en: 'Region', vn: 'Vùng' },
      { en: 'River', vn: 'Sông' },
      { en: 'Sand', vn: 'Cát' },
      { en: 'Seaside', vn: 'Vùng biển' },
      { en: 'Stream', vn: 'Suối' },
      { en: 'Valley', vn: 'Thung lũng' }
    ]
  },
  {
    id: 'cinema',
    name: '11. Chủ đề điện ảnh',
    words: [
      { en: 'Background', vn: 'Bối cảnh' },
      { en: 'Book a ticket', vn: 'Đặt vé' },
      { en: 'Box office', vn: 'Quầy vé' },
      { en: 'Cinema', vn: 'Rạp chiếu phim' },
      { en: 'Combo', vn: 'Gói sản phẩm giá rẻ' },
      { en: 'New release', vn: 'Phim mới ra' },
      { en: 'Now showing', vn: 'Phim đang chiếu' },
      { en: 'Plot', vn: 'Cốt truyện' },
      { en: 'Popcorn', vn: 'Bỏng ngô' },
      { en: 'Photo booth', vn: 'Bốt chụp ảnh' },
      { en: 'Red carpet', vn: 'Thảm đỏ' },
      { en: 'Row', vn: 'Hàng ghế' },
      { en: 'Scene', vn: 'Cảnh quay' },
      { en: 'Seat', vn: 'Chỗ ngồi' },
      { en: 'Screen', vn: 'Màn hình' },
      { en: 'Ticket', vn: 'Vé' },
      { en: 'Trailer', vn: 'Đoạn giới thiệu phim' }
    ]
  },
  {
    id: 'shopping',
    name: '12. Chủ đề mua sắm',
    words: [
      { en: 'Corner shop', vn: 'Cửa hàng nhỏ lẻ' },
      { en: 'Department store', vn: 'Cửa hàng tạp hoá' },
      { en: 'Discount store', vn: 'Cửa hàng giảm giá' },
      { en: 'E-commerce', vn: 'Thương mại điện tử' },
      { en: 'Flea market', vn: 'Chợ trời' },
      { en: 'Franchise', vn: 'Cửa hàng miễn thuế' },
      { en: 'High-street name', vn: 'Cửa hàng nổi tiếng' },
      { en: 'Mall', vn: 'Trung tâm mua sắm' },
      { en: 'Pet shop', vn: 'Cửa hàng thú cưng' },
      { en: 'Shopping channel', vn: 'Kênh mua sắm' },
      { en: 'Supermarket', vn: 'Siêu thị' },
      { en: 'Up-market', vn: 'Thị trường cao cấp' },
      { en: 'Bill', vn: 'Hoá đơn' },
      { en: 'Cash', vn: 'Tiền mặt' },
      { en: 'Cashier', vn: 'Thu ngân' },
      { en: 'Cash register', vn: 'Máy đếm tiền mặt' },
      { en: 'Change', vn: 'Tiền trả lại' },
      { en: 'Checkout', vn: 'Quầy thu tiền' },
      { en: 'Coin', vn: 'Tiền xu' },
      { en: 'Coupon', vn: 'Phiếu giảm giá' },
      { en: 'Credit card', vn: 'Thẻ tín dụng' },
      { en: 'Department', vn: 'Gian hàng' },
      { en: 'Leaflet', vn: 'Tờ rơi' },
      { en: 'Manager', vn: 'Người quản lí' },
      { en: 'Member card', vn: 'Thẻ thành viên' },
      { en: 'Price', vn: 'Giá' },
      { en: 'Queue', vn: 'Xếp hàng' },
      { en: 'Receipt', vn: 'Giấy biên nhận' },
      { en: 'Refund', vn: 'Hoàn tiền' },
      { en: 'Return', vn: 'Sự trả lại hàng' },
      { en: 'Shop assistant', vn: 'Nhân viên cửa hàng' },
      { en: 'Aisle', vn: 'Lối đi giữa các quầy hàng' },
      { en: 'Fitting room', vn: 'Phòng thử đồ' },
      { en: 'Plastic bag', vn: 'Túi ni-long' },
      { en: 'Shelf', vn: 'Kệ, giá' },
      { en: 'Shopping bag', vn: 'Túi mua hàng' },
      { en: 'Shop window', vn: 'Cửa kính trưng bày hàng' },
      { en: 'Stockroom', vn: 'Kho chứa hàng' },
      { en: 'Trolley', vn: 'Xe đẩy hàng' }
    ]
  },
  {
    id: 'time',
    name: '13. Chủ đề thời gian',
    words: [
      { en: 'Afternoon', vn: 'Buổi chiều' },
      { en: 'Autumn', vn: 'Mùa thu' },
      { en: 'Birthday', vn: 'Sinh nhật' },
      { en: 'Clock', vn: 'Giờ' },
      { en: 'Date/ Day', vn: 'Ngày' },
      { en: 'Evening', vn: 'Buổi tối' },
      { en: 'Hour', vn: 'Giờ' },
      { en: 'Monthly', vn: 'Hằng tháng' },
      { en: 'Morning', vn: 'Buổi sáng' },
      { en: 'Minute', vn: 'Phút' },
      { en: 'Midnight', vn: 'Nửa đêm' },
      { en: 'Midday', vn: 'Giữa trưa' },
      { en: 'Night', vn: 'Đêm' },
      { en: 'Noon', vn: 'Buổi trưa' },
      { en: 'Second', vn: 'Giây' },
      { en: 'Spring', vn: 'Mùa xuân' },
      { en: 'Summer', vn: 'Mùa hè' },
      { en: 'Time', vn: 'Thời gian' },
      { en: 'Weekday', vn: 'Ngày thường' },
      { en: 'Weekend', vn: 'Cuối tuần' },
      { en: 'Working hours', vn: 'Giờ làm việc' },
      { en: 'Winter', vn: 'Mùa đông' }
    ]
  },
  {
    id: 'transport',
    name: '14. Chủ đề phương tiện giao thông',
    words: [
      { en: 'Bicycle / Bike', vn: 'Xe đạp' },
      { en: 'Car', vn: 'Ô tô, xe hơi' },
      { en: 'Motorbike', vn: 'Xe máy' },
      { en: 'Minicab', vn: 'Xe cho thuê' },
      { en: 'Moped', vn: 'Xe máy có bàn đạp' },
      { en: 'Scooter', vn: 'Xe tay ga' },
      { en: 'Van', vn: 'Xe tải kích thước nhỏ' },
      { en: 'Boat', vn: 'Thuyền' },
      { en: 'Cargo ship', vn: 'Tàu chở hàng hoá' },
      { en: 'Cruise ship', vn: 'Du thuyền' },
      { en: 'Ferry', vn: 'Phà' },
      { en: 'Rowing boat', vn: 'Thuyền buồm có mái chèo' },
      { en: 'Sailboat', vn: 'Thuyền buồm' },
      { en: 'Ship', vn: 'Tàu' },
      { en: 'Speedboat', vn: 'Tàu siêu tốc' },
      { en: 'Bus', vn: 'Xe buýt' },
      { en: 'Coach', vn: 'Xe khách' },
      { en: 'Railway train', vn: 'Tàu hoả' },
      { en: 'Subway', vn: 'Tàu điện ngầm' },
      { en: 'Taxi', vn: 'Xe taxi' },
      { en: 'Tube', vn: 'Tàu điện ngầm (ở Anh)' },
      { en: 'Underground', vn: 'Tàu điện ngầm' },
      { en: 'Airplane', vn: 'Máy bay' },
      { en: 'Glider', vn: 'Tàu lượn' },
      { en: 'Helicopter', vn: 'Trực thăng' },
      { en: 'Hot-air balloon', vn: 'Khinh khí cầu' }
    ]
  },
  {
    id: 'weather',
    name: '15. Chủ đề thời tiết',
    words: [
      { en: 'Bright', vn: 'Sáng sủa' },
      { en: 'Clear', vn: 'Trong trẻo, quang đãng' },
      { en: 'Cloudy', vn: 'Nhiều mây' },
      { en: 'Dry', vn: 'Hanh khô' },
      { en: 'Foggy', vn: 'Sương mù' },
      { en: 'Fine', vn: 'Không mây không mưa' },
      { en: 'Gloomy', vn: 'Ảm đạm' },
      { en: 'Haze', vn: 'Sương mỏng' },
      { en: 'Humid', vn: 'Ẩm' },
      { en: 'Mild', vn: 'Ôn hòa' },
      { en: 'Overcast', vn: 'Âm u' },
      { en: 'Partially cloudy', vn: 'Có mây và trời xanh' },
      { en: 'Sunny', vn: 'Nhiều nắng' },
      { en: 'Wet', vn: 'Ẩm ướt' },
      { en: 'Windy', vn: 'Nhiều gió' },
      { en: 'Baking hot', vn: 'Nóng như thiêu' },
      { en: 'Cold', vn: 'Lạnh' },
      { en: 'Chilly', vn: 'Lạnh thấu xương' },
      { en: 'Celsius', vn: 'Độ C' },
      { en: 'Degree', vn: 'Độ' },
      { en: 'Downpour', vn: 'Mưa lớn' },
      { en: 'Frosty', vn: 'Đầy sương giá' },
      { en: 'Freeze', vn: 'Đóng băng' },
      { en: 'Hot', vn: 'Nóng' },
      { en: 'Temperature', vn: 'Nhiệt độ' },
      { en: 'Rainfall', vn: 'Lượng mưa' },
      { en: 'Blizzard', vn: 'Bão tuyết' },
      { en: 'Blustery', vn: 'Gió mạnh' },
      { en: 'Drizzle', vn: 'Mưa phùn' },
      { en: 'Flood', vn: 'Lũ lụt' },
      { en: 'Hail', vn: 'Mưa đá' },
      { en: 'Hurricane', vn: 'Bão lớn' },
      { en: 'Gale', vn: 'Gió giật' },
      { en: 'Lightning', vn: 'Tia chớp' },
      { en: 'Mist', vn: 'Sương muối' },
      { en: 'Rain', vn: 'Mưa' },
      { en: 'Rain-storm', vn: 'Mưa bão' },
      { en: 'Shower', vn: 'Mưa rào' },
      { en: 'Snow', vn: 'Tuyết' },
      { en: 'Snowstorm', vn: 'Bão tuyết' },
      { en: 'Snowflake', vn: 'Bông tuyết' },
      { en: 'Thunder', vn: 'Sấm sét' },
      { en: 'Thunderstorm', vn: 'Giông bão' }
    ]
  },
  {
    id: 'environment',
    name: '16. Chủ đề môi trường',
    words: [
      { en: 'Acid rain', vn: 'Mưa a-xít' },
      { en: 'Climate change', vn: 'Biến đổi khí hậu' },
      { en: 'Deforestation', vn: 'Sự phá rừng' },
      { en: 'Dust', vn: 'Bụi' },
      { en: 'Emission', vn: 'Chất thải' },
      { en: 'Erosion', vn: 'Xói mòn' },
      { en: 'Fertilizer', vn: 'Phân bón' },
      { en: 'Forest', vn: 'Rừng' },
      { en: 'Forestation', vn: 'Trồng rừng' },
      { en: 'Global warming', vn: 'Sự nóng lên toàn cầu' },
      { en: 'Oil spill', vn: 'Hiện tượng tràn dầu' },
      { en: 'Plastic bag', vn: 'Túi nilon' },
      { en: 'Pollution', vn: 'Sự ô nhiễm' },
      { en: 'Sewage', vn: 'Nước thải' },
      { en: 'Smoke', vn: 'Khói' },
      { en: 'Waste', vn: 'Rác thải' },
      { en: 'Air pollution', vn: 'Ô nhiễm không khí' },
      { en: 'Noise pollution', vn: 'Ô nhiễm tiếng ồn' },
      { en: 'Radioactive pollution', vn: 'Ô nhiễm phóng xạ' },
      { en: 'Light pollution', vn: 'Ô nhiễm ánh sáng' },
      { en: 'Soil pollution', vn: 'Ô nhiễm đất' },
      { en: 'Thermal pollution', vn: 'Ô nhiễm nhiệt' },
      { en: 'Water pollution', vn: 'Ô nhiễm nước' },
      { en: 'Biogas', vn: 'Khí sinh học' },
      { en: 'Charcoal', vn: 'Than' },
      { en: 'Coal', vn: 'Than đá' },
      { en: 'Diamond', vn: 'Kim cương' },
      { en: 'Electricity', vn: 'Điện' },
      { en: 'Fossil', vn: 'Hoá thạch' },
      { en: 'Gemstone', vn: 'Đá quý' },
      { en: 'Gold', vn: 'Vàng' },
      { en: 'Gold mine', vn: 'Quặng vàng' },
      { en: 'Hydropower', vn: 'Thuỷ điện' },
      { en: 'Mineral', vn: 'Khoáng sản' },
      { en: 'Nuclear power', vn: 'Năng lượng hạt nhân' },
      { en: 'Oil mine', vn: 'Quặng dầu' },
      { en: 'Petroleum', vn: 'Dầu mỏ' },
      { en: 'Silver', vn: 'Bạc' },
      { en: 'Solar power', vn: 'Năng lượng mặt trời' },
      { en: 'Water power', vn: 'Năng lượng nước' },
      { en: 'Wave power', vn: 'Năng lượng sóng' },
      { en: 'Wind power', vn: 'Năng lượng gió' },
      { en: 'Wood', vn: 'Gỗ' }
    ]
  },
  {
    id: 'entertainment',
    name: '17. Chủ đề giải trí',
    words: [
      { en: 'Chat with friends', vn: 'Tán gẫu với bạn bè' },
      { en: 'Collect things', vn: 'Sưu tầm đồ' },
      { en: 'Do arts and crafts', vn: 'Chơi cắt dán' },
      { en: 'Do sports', vn: 'Chơi thể thao' },
      { en: 'Draw pictures', vn: 'Vẽ tranh' },
      { en: 'Fly kites', vn: 'Thả diều' },
      { en: 'Go camping', vn: 'Đi cắm trại' },
      { en: 'Go to the cinema', vn: 'Đi xem phim ở rạp' },
      { en: 'Go to the theatre', vn: 'Đi xem kịch' },
      { en: 'Go shopping', vn: 'Mua sắm' },
      { en: 'Hangout with friends', vn: 'Ra ngoài chơi' },
      { en: 'Hunt', vn: 'Săn bắn' },
      { en: 'Listen to music', vn: 'Nghe nhạc' },
      { en: 'Play chess', vn: 'Chơi cờ vua' },
      { en: 'Read books', vn: 'Đọc sách' },
      { en: 'Ride a bike', vn: 'Đạp xe' },
      { en: 'Sew', vn: 'May vá' },
      { en: 'Sing', vn: 'Hát hò' },
      { en: 'Swim', vn: 'Bơi lội' },
      { en: 'Watch TV', vn: 'Xem ti vi' },
      { en: 'Billiards', vn: 'Trò chơi bida' },
      { en: 'Board game', vn: 'Trò chơi có bàn cờ' },
      { en: 'Card games', vn: 'Trò chơi bài' },
      { en: 'Chess', vn: 'Cờ vua' },
      { en: 'Dominoes', vn: 'Cờ domino' },
      { en: 'Jigsaw puzzle', vn: 'Trò ghép hình' },
      { en: 'Bird-watching', vn: 'Ngắm chim' },
      { en: 'Camping', vn: 'Cắm trại' },
      { en: 'Fishing', vn: 'Câu cá' },
      { en: 'Hiking', vn: 'Leo núi' },
      { en: 'Hunting', vn: 'Săn bắn' },
      { en: 'Climbing', vn: 'Leo núi' },
      { en: 'Scuba diving', vn: 'Lặn có bình khí' },
      { en: 'Backpacking', vn: 'Du lịch bụi' }
    ]
  }
];